#!/usr/bin/env php
<?php
/**
 * Passbolt restore script
 *
 * Reads restore/passbolt.php, generates .env, starts Docker Compose,
 * then copies GPG keys into the running Passbolt container.
 *
 * Usage: php restore-passbolt.php
 */

define('CONFIG', __DIR__ . '/restore');
define('DS', DIRECTORY_SEPARATOR);

// -------------------------------------------------------------------------
// 1. Load passbolt.php
// -------------------------------------------------------------------------
$configFile = CONFIG . DS . 'passbolt.php';
if (!file_exists($configFile)) {
    die("Error: restore/passbolt.php not found.\n");
}

$config = include $configFile;

// -------------------------------------------------------------------------
// 2. Extract values
// -------------------------------------------------------------------------
$db       = $config['Datasources']['default'] ?? [];
$host     = $db['host']     ?? '127.0.0.1';
$database = $db['database'] ?? '';
$username = $db['username'] ?? '';
$password = $db['password'] ?? '';

$fullBaseUrl = $config['App']['fullBaseUrl'] ?? '';
if (empty($fullBaseUrl)) {
    die("Error: App.fullBaseUrl not found in passbolt.php.\n");
}

// Extract domain from fullBaseUrl for the TLS certificate CN
$domain = parse_url($fullBaseUrl, PHP_URL_HOST);
if (empty($domain)) {
    die("Error: Could not parse domain from fullBaseUrl: $fullBaseUrl\n");
}

// -------------------------------------------------------------------------
// 3. Write .env
// -------------------------------------------------------------------------
$env = <<<ENV
# Auto-generated by restore-passbolt.php — do not edit manually

# Database
MYSQL_DATABASE={$database}
MYSQL_USER={$username}
MYSQL_PASSWORD={$password}

# Passbolt
APP_FULL_BASE_URL={$fullBaseUrl}
PASSBOLT_DOMAIN={$domain}
ENV;

file_put_contents(__DIR__ . '/.env', $env);
echo ".env written OK\n";

// -------------------------------------------------------------------------
// 4. Start Docker Compose
// -------------------------------------------------------------------------
echo "Starting containers...\n";
passthru('docker compose up -d', $exitCode);
if ($exitCode !== 0) {
    die("Error: docker compose up failed.\n");
}

// -------------------------------------------------------------------------
// 5. Wait for the Passbolt container to be running
// -------------------------------------------------------------------------
echo "Waiting for Passbolt container to be ready...\n";
$container = null;
for ($i = 0; $i < 30; $i++) {
    $output = shell_exec('docker compose ps -q passbolt');
    $container = trim($output ?? '');
    if (!empty($container)) break;
    sleep(2);
}
if (empty($container)) {
    die("Error: Could not find running Passbolt container.\n");
}
echo "Passbolt container ID: $container\n";

// -------------------------------------------------------------------------
// 6. Copy GPG keys into the container and set correct permissions
// -------------------------------------------------------------------------
echo "Restoring GPG and JWT keys...\n";

$gpgDir   = CONFIG . DS . 'gpg';
$pubKey   = $gpgDir . DS . 'serverkey.asc';
$privKey  = $gpgDir . DS . 'serverkey_private.asc';

if (!file_exists($pubKey) || !file_exists($privKey)) {
    die("Error: GPG key files not found in restore/gpg/.\n");
}

$jwtDir     = CONFIG . DS . 'jwt';
$jwtPrivKey = $jwtDir . DS . 'jwt.key';
$jwtPubKey  = $jwtDir . DS . 'jwt.pem';

if (!file_exists($jwtPrivKey) || !file_exists($jwtPubKey)) {
    die("Error: JWT key files not found in restore/jwt/.\n");
}

$commands = [
    // GPG keys
    "docker cp {$pubKey} {$container}:/etc/passbolt/gpg/serverkey.asc",
    "docker cp {$privKey} {$container}:/etc/passbolt/gpg/serverkey_private.asc",
    "docker exec {$container} chown www-data:www-data /etc/passbolt/gpg/serverkey.asc",
    "docker exec {$container} chown www-data:www-data /etc/passbolt/gpg/serverkey_private.asc",
    "docker exec {$container} chmod 440 /etc/passbolt/gpg/serverkey.asc",
    "docker exec {$container} chmod 440 /etc/passbolt/gpg/serverkey_private.asc",
    // JWT keys
    "docker cp {$jwtPrivKey} {$container}:/etc/passbolt/jwt/jwt.key",
    "docker cp {$jwtPubKey} {$container}:/etc/passbolt/jwt/jwt.pem",
    "docker exec {$container} chown www-data:www-data /etc/passbolt/jwt/jwt.key",
    "docker exec {$container} chown www-data:www-data /etc/passbolt/jwt/jwt.pem",
    "docker exec {$container} chmod 440 /etc/passbolt/jwt/jwt.key",
    "docker exec {$container} chmod 440 /etc/passbolt/jwt/jwt.pem",
];

foreach ($commands as $cmd) {
    passthru($cmd, $exitCode);
    if ($exitCode !== 0) {
        die("Error running: $cmd\n");
    }
}

echo "\nRestore complete. Run the healthcheck to verify:\n";
echo "  docker exec {$container} su -s /bin/bash www-data -c \"bin/cake passbolt healthcheck\"\n";
