#!/usr/bin/env php
<?php
/**
 * Passbolt restore script
 *
 * Reads restore/passbolt.php, generates .env, starts Docker Compose,
 * then copies GPG keys into the running Passbolt container.
 *
 * Usage: php restore-passbolt.php
 */

define('CONFIG', __DIR__ . '/restore');
define('DS', DIRECTORY_SEPARATOR);

// -------------------------------------------------------------------------
// Load passbolt.php
// -------------------------------------------------------------------------
$configFile = CONFIG . DS . 'passbolt.php';
if (!file_exists($configFile)) {
    die("Error: restore/passbolt.php not found.\n");
}

$config = include $configFile;

// -------------------------------------------------------------------------
// Extract values
// -------------------------------------------------------------------------
$db       = $config['Datasources']['default'] ?? [];
$host     = $db['host']     ?? '127.0.0.1';
$database = $db['database'] ?? '';
$username = $db['username'] ?? '';
$password = $db['password'] ?? '';

$fullBaseUrl = $config['App']['fullBaseUrl'] ?? '';
if (empty($fullBaseUrl)) {
    die("Error: App.fullBaseUrl not found in passbolt.php.\n");
}

// Extract domain from fullBaseUrl for the TLS certificate CN
$domain = parse_url($fullBaseUrl, PHP_URL_HOST);
if (empty($domain)) {
    die("Error: Could not parse domain from fullBaseUrl: $fullBaseUrl\n");
}

// -------------------------------------------------------------------------
// Patch passbolt.php — replace the original DB host with 'db'
// -------------------------------------------------------------------------
$passboltPhpContent = file_get_contents($configFile);
$patched = preg_replace(
    "/(\'Datasources\'\s*=>\s*\[\s*\'default\'\s*=>\s*\[\s*[^]]*?\'host\'\s*=>\s*\')([^\']+)(\')/" ,
    '${1}db${3}',
    $passboltPhpContent
);

if ($patched === null) {
    die("Error: Could not patch host in passbolt.php. Please check the file format.\n");
} elseif ($patched === $passboltPhpContent) {
    echo "passbolt.php host already set to 'db', skipping patch\n";
} else {
    file_put_contents($configFile, $patched);
    echo "passbolt.php patched: host replaced with 'db'\n";
}

// -------------------------------------------------------------------------
// Patch passbolt.php — disable ssl.force (nginx handles SSL termination)
// -------------------------------------------------------------------------
$passboltPhpContent = file_get_contents($configFile);
$patched = preg_replace(
    "/('ssl'\s*=>\s*\[\s*'force'\s*=>\s*)true/",
    '${1}false',
    $passboltPhpContent
);

if ($patched === null) {
    die("Error: Could not patch ssl.force in passbolt.php.\n");
} elseif ($patched === $passboltPhpContent) {
    echo "passbolt.php ssl.force already false or not found, skipping patch\n";
} else {
    file_put_contents($configFile, $patched);
    echo "passbolt.php patched: ssl.force set to false\n";
}

// -------------------------------------------------------------------------
// Write .env
// -------------------------------------------------------------------------
$env = <<<ENV
# Auto-generated by restore-passbolt.php — do not edit manually

# Database
MYSQL_DATABASE={$database}
MYSQL_USER={$username}
MYSQL_PASSWORD={$password}

# Passbolt
APP_FULL_BASE_URL={$fullBaseUrl}
PASSBOLT_DOMAIN={$domain}
ENV;

file_put_contents(__DIR__ . '/.env', $env);
echo ".env written OK\n";

// -------------------------------------------------------------------------
// Copy SSL certificates into the cert_data volume
// -------------------------------------------------------------------------
$sslDir    = CONFIG . DS . 'ssl';
$fullchain = $sslDir . DS . 'fullchain.pem';
$privkey   = $sslDir . DS . 'privkey.pem';

if (!file_exists($fullchain) || !file_exists($privkey)) {
    die("Error: SSL certificates not found in restore/ssl/. Please copy fullchain.pem and privkey.pem from your production server.\n");
}

echo "Copying SSL certificates into cert_data volume...\n";
$sslDirReal = realpath($sslDir);
// Convert Windows path to Docker-compatible path (e.g. C:\foo -> /c/foo)
$sslDirReal = preg_replace('/^([A-Za-z]):/', '/$1', str_replace('\\', '/', $sslDirReal));

$sslCommands = [
    "docker run --rm -v passbolt-restore_cert_data:/certs -v {$sslDirReal}:/src alpine cp /src/fullchain.pem /certs/fullchain.pem",
    "docker run --rm -v passbolt-restore_cert_data:/certs -v {$sslDirReal}:/src alpine cp /src/privkey.pem /certs/privkey.pem",
];
foreach ($sslCommands as $cmd) {
    passthru($cmd, $exitCode);
    if ($exitCode !== 0) {
        die("Error copying SSL certificates.\n");
    }
}
if ($exitCode !== 0) {
    die("Error copying SSL certificates.\n");
}
echo "SSL certificates copied OK\n";

// -------------------------------------------------------------------------
// Start Docker Compose
// -------------------------------------------------------------------------
echo "Starting containers...\n";
passthru('docker compose up -d', $exitCode);
if ($exitCode !== 0) {
    die("Error: docker compose up failed.\n");
}

// -------------------------------------------------------------------------
// Wait for the Passbolt container to be running
// -------------------------------------------------------------------------
echo "Waiting for Passbolt container to be ready...\n";
$container = null;
for ($i = 0; $i < 30; $i++) {
    $output = shell_exec('docker compose ps -q passbolt');
    $container = trim($output ?? '');
    if (!empty($container)) break;
    sleep(2);
}
if (empty($container)) {
    die("Error: Could not find running Passbolt container.\n");
}
echo "Passbolt container ID: $container\n";

// -------------------------------------------------------------------------
// Copy GPG keys into the container and set correct permissions
// -------------------------------------------------------------------------
echo "Restoring GPG and JWT keys...\n";

$gpgDir   = CONFIG . DS . 'gpg';
$pubKey   = $gpgDir . DS . 'serverkey.asc';
$privKey  = $gpgDir . DS . 'serverkey_private.asc';

if (!file_exists($pubKey) || !file_exists($privKey)) {
    die("Error: GPG key files not found in restore/gpg/.\n");
}

$jwtDir     = CONFIG . DS . 'jwt';
$jwtPrivKey = $jwtDir . DS . 'jwt.key';
$jwtPubKey  = $jwtDir . DS . 'jwt.pem';

if (!file_exists($jwtPrivKey) || !file_exists($jwtPubKey)) {
    die("Error: JWT key files not found in restore/jwt/.\n");
}

$commands = [
    // GPG keys
    "docker cp {$pubKey} {$container}:/etc/passbolt/gpg/serverkey.asc",
    "docker cp {$privKey} {$container}:/etc/passbolt/gpg/serverkey_private.asc",
    "docker exec --user root {$container} chown www-data:www-data /etc/passbolt/gpg/serverkey.asc",
    "docker exec --user root {$container} chown www-data:www-data /etc/passbolt/gpg/serverkey_private.asc",
    "docker exec --user root {$container} chmod 440 /etc/passbolt/gpg/serverkey.asc",
    "docker exec --user root {$container} chmod 440 /etc/passbolt/gpg/serverkey_private.asc",
    // JWT keys
    "docker cp {$jwtPrivKey} {$container}:/etc/passbolt/jwt/jwt.key",
    "docker cp {$jwtPubKey} {$container}:/etc/passbolt/jwt/jwt.pem",
    "docker exec --user root {$container} chown root:www-data /etc/passbolt/jwt/jwt.key",
    "docker exec --user root {$container} chown root:www-data /etc/passbolt/jwt/jwt.pem",
    "docker exec --user root {$container} chmod 440 /etc/passbolt/jwt/jwt.key",
    "docker exec --user root {$container} chmod 440 /etc/passbolt/jwt/jwt.pem",
    // JWT directory permissions
    "docker exec --user root {$container} chown root:www-data /etc/passbolt/jwt",
    "docker exec --user root {$container} chmod 550 /etc/passbolt/jwt",
];

foreach ($commands as $cmd) {
    passthru($cmd, $exitCode);
    if ($exitCode !== 0) {
        die("Error running: $cmd\n");
    }
}

echo "\nRestore complete. Run the healthcheck to verify:\n";
echo "  docker exec --user www-data {$container} bin/cake passbolt healthcheck\n";
